dist: trusty

matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-5" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-6" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-7" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-8" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-8" CXX_STANDARD=17
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-3.7" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - clang-3.7
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-4.0" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-5.0" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-6.0" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
        - clang-6.0
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-7" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-7
        packages:
        - clang-7
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" CXX_STANDARD=11
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-8
        packages:
        - clang-8
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-8" CXX_STANDARD=17
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-8
        packages:
        - clang-8
        - libboost-all-dev
  - os: osx
    language: cpp
    compiler: clang
    env: CXX_STANDARD=11

script:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir -p cmake
    travis_retry wget "https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.tar.gz"
    tar xf cmake-3.11.2-Linux-x86_64.tar.gz -C cmake --strip-components=1
    export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
  else
    brew upgrade cmake
  fi
- cmake --version
- mkdir build
- cd build
- git clone https://github.com/toml-lang/toml.git
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_CXX_STANDARD=$CXX_STANDARD ..
- make
- ctest --output-on-failure
