version: 2.1

jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run: g++ --version
      - run: cd tests/
      - run: g++ -std=c++11 -O2 -Wall -Wextra -Werror check.cpp -o check
      - run: git clone https://github.com/BurntSushi/toml-test.git
      - run: cp check toml-test/tests/invalid
      - run: cp check toml-test/tests/valid
      - run: cd toml-test/tests/invalid
      - run: for f in $(ls ./*.toml); do echo "==> ${f}"; cat ${f}; ./check ${f} invalid; done
      - run: cd ../valid
      - run: for f in $(ls ./*.toml); do echo "==> ${f}"; cat ${f}; ./check ${f} valid; done

workflows:
  version: 2.1
  test:
    jobs:
      - test
